# Generated by Django 4.1.2 on 2022-10-12 21:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('ethmain', 'Ethereum (ETH)'), ('goerli', 'Goerli (GOR)')], default='goerli', max_length=7)),
                ('name', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=8)),
                ('second_mint_price', models.DecimalField(decimal_places=9, max_digits=10)),
                ('supply', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(1)])),
                ('royalty_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('whitelist', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
