# Generated by Django 4.1.2 on 2022-10-13 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
