# Generated by Django 4.1.2 on 2022-10-13 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='date_created',
        ),
        migrations.AddField(
            model_name='contract',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
