# Generated by Django 4.1.2 on 2022-10-15 20:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contract_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tsty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('ethmain', 'Ethereum (ETH)'), ('goerli', 'Goerli (GOR)')], default='goerli', max_length=7)),
                ('name', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=8)),
                ('second_mint_price', models.DecimalField(decimal_places=9, max_digits=10)),
                ('supply', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(1)])),
                ('royalty_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('whitelist', models.BooleanField()),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
