# Generated by Django 4.1.2 on 2022-10-17 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0008_delete_tsty_alter_contract_owner_alter_easy_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easy',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='easys', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
