# Generated by Django 4.1.2 on 2022-11-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_alter_contract_owner_delete_easy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='created_on',
        ),
    ]
