# Generated by Django 4.1.2 on 2022-11-01 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_remove_contract_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
